version: "3.8"

services:
  monolith:
    build:
      context: ../monolith
      dockerfile: Dockerfile
    container_name: hotelio-monolith
    ports:
      - "8084:8080"
    networks:
      - hotelio-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://monolith-db:5432/hotelio
      SPRING_DATASOURCE_USERNAME: hotelio
      SPRING_DATASOURCE_PASSWORD: hotelio
      BOOKING_SERVICE_EXTERNAL_HOST: booking-service
      BOOKING_SERVICE_EXTERNAL_PORT: 50051
    depends_on:
      - monolith-db

  monolith-db:
    image: postgres:15
    container_name: hotelio-db
    environment:
      POSTGRES_USER: hotelio
      POSTGRES_PASSWORD: hotelio
      POSTGRES_DB: hotelio
    ports:
      - "5432:5432"
    volumes:
      - monolith-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

  booking-service:
    build:
      context: ./results/booking-service/
      dockerfile: docker/Dockerfile
    ports:
      - "50051:50051"
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@booking-db:5432/booking"
      GRPC_HOST: "0.0.0.0"
      GRPC_PORT: "50051"
      USER_SERVICE_URL: "http://monolith:8080"
      HOTEL_SERVICE_URL: "http://monolith:8080"
      REVIEW_SERVICE_URL: "http://monolith:8080"
      PROMO_SERVICE_URL: "http://monolith:8080"
      LOG_LEVEL: "INFO"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_TOPIC: "booking-events"
    depends_on:
      - booking-db
      - kafka
    networks:
      - hotelio-net

  booking-db:
    image: postgres:15
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

  booking-history-service:
    build:
      context: ./results/booking-history-service/
      dockerfile: docker/Dockerfile
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@booking-history-db:5432/booking_history"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_TOPIC: "booking-events"
      KAFKA_GROUP_ID: "booking-history-service"
      LOG_LEVEL: "INFO"
    depends_on:
      - booking-history-db
      - kafka
    networks:
      - hotelio-net

  booking-history-db:
    image: postgres:15
    environment:
      POSTGRES_DB: booking_history
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - booking-history-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - hotelio-net

  kafbat-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8085:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - hotelio-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - hotelio-net

volumes:
  monolith-db-data:
  booking-db-data:
  booking-history-db-data:

networks:
  hotelio-net:
    external: true
