version: '3.8'

services:
  apollo-gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - booking-subgraph
      - hotel-subgraph
    networks:
      - hotelio-net

  booking-subgraph:
    build: ./booking-subgraph
    ports:
      - "4001:4001"
    environment:
      BOOKING_SERVICE_HOST: booking-service
      BOOKING_SERVICE_PORT: 50051
    networks:
      - hotelio-net

  hotel-subgraph:
    build: ./hotel-subgraph
    ports:
      - "4002:4002"
    environment:
      HOTEL_SERVICE_URL: http://hotelio-monolith:8080
    networks:
      - hotelio-net

networks:
  hotelio-net:
    external: true
